#ifndef __MESSAGE_H
#define __MESSAGE_H	

typedef enum{
	MESSAGE_NULL,
	MESSAGE_USART_LOOP,
	MESSAGE_MSG_TEST,
	MESSAGE_EEPROM_WRITE,
	MESSAGE_EEPROM_READ,
	MESSAGE_CAN_WRITE,
	MESSAGE_CAN_READ,
} Message_TypeDef;

#endif
